[project]
name = "iit"
version = "0.1.0"
description = "Integrated Information Theory in LLM project"
readme = "README.md"
requires-python = "==3.11.15"

dependencies = [
    "transformers",
    "datasets",
    "peft",
    "trl",
    "pyphi @ git+https://github.com/wmayner/pyphi.git@feature/iit-4.0",
    "scikit-learn",
    "tensorboard",
    "torch-tb-profiler",
    "bitsandbytes",
    "deepspeed",
    "math-verify",
    "matplotlib",
    "huggingface-hub",
    "torch",
    "trl==1.6.0",
    "vllm==0.13.0",
    "jsonlines",
    "human-eval",
    "fire",
    "numpy",
    "pandas",
]

[tool.uv.sources]
human-eval = { path = "./human-eval", editable = true }

